=== NaveenParala/restfull/registerService_ReqXsd/target/classes/RegisterSvc_Req.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.o2.org/RegisterSvc/schema/Req"
	xmlns:req="http://www.o2.org/RegisterSvc/schema/Req"
	elementFormDefault="qualified">
	<element name="RegisterSvcReq" type="req:RegisterServiceReqType" />
	<complexType name="RegisterServiceReqType">
		<sequence>
			<element name="ClientDetails" type="req:ClientDetailsType" />
			<element name="CardDetails" type="req:CardDetailsType" />
			<element name="AccountDetails" type="req:AccountDetailsType" />
			<element name="ServiceDetails" type="req:ServiceDetailsType" />
		</sequence>
	</complexType>
	<complexType name="ClientDetailsType">
		<sequence>
			<element name="clientId" type="string" />
			<element name="channelId" type="string" />
			<element name="regId" type="string" />
		</sequence>
	</complexType>

	<complexType name="CardDetailsType">
		<sequence>
			<element name="cardNum" type="string" />
			<element name="cvv" type="string" />
			<element name="expDate" type="string" />
			<element name="nameOnCard" type="string" />
		</sequence>
	</complexType>

	<complexType name="AccountDetailsType">
		<sequence>
			<element name="accountNum" type="string" />
			<element name="mobile" type="string" />
		</sequence>
	</complexType>

	<complexType name="ServiceDetailsType">
		<sequence>
			<element name="serviceName" type="string" />
			<element name="apiName" type="string" />
			<element name="version" type="string" />
		</sequence>
	</complexType>


</schema>

=== NaveenParala/restfull/regsvc_xsd/target/classes/RegisterSvc_Req.xml
<?xml version="1.0" encoding="UTF-8"?>
<req:RegisterSvcReq xmlns:req="http://www.o2.org/RegisterSvc/schema/Req" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.o2.org/RegisterSvc/schema/Req RegisterSvc_Req.xsd ">
  <req:ClientDetails>
    <req:clientId>req:clientId</req:clientId>
    <req:channelId>req:channelId</req:channelId>
    <req:regId>req:regId</req:regId>
  </req:ClientDetails>
  <req:CardDetails>
    <req:cardNum>req:cardNum</req:cardNum>
    <req:cvv>req:cvv</req:cvv>
    <req:expDate>req:expDate</req:expDate>
    <req:nameOnCard>req:nameOnCard</req:nameOnCard>
  </req:CardDetails>
  <req:AccountDetails>
    <req:accountNum>req:accountNum</req:accountNum>
    <req:mobile>req:mobile</req:mobile>
  </req:AccountDetails>
  <req:ServiceDetails>
    <req:serviceName>req:serviceName</req:serviceName>
    <req:apiName>req:apiName</req:apiName>
    <req:version>req:version</req:version>
  </req:ServiceDetails>
</req:RegisterSvcReq>
